### ISSUE TITLE
Phase out the crafted saddle

### ISSUE THREAD

**Issue by IcarussOne** [Elite-Modding-Team/MoCreaturesExtended#10]
It was presumably made back then because they couldn't get the regular saddle to work with the horses and it used to only be found in dungeon chests. Now that the vanilla saddle has multiple uses and is found more easily, I think the crafted saddle should be removed and instead just have the vanilla saddle be utilized. A recipe (configurable) could also be added to craft more saddles.

**Comment by xJon** [comment]
I think it's a good idea to reconsider this as things have indeed changed since the item was first introduced.
After thinking about this for a bit, I believe it's best to keep things as-is whilst making sure both types of saddles work on all Mo' Creatures mobs. Then you just have an alt saddle variant that's always craftable, which was the original intent. The alternative of removing it, makes you lose the alt texture, alongside either removing the craftability feature, or forcing it on the vanilla saddle which might be more intrusive to modpacks with other mods and unexpected situations.
Also due to the vanilla saddle working with Mo' Creatures mobs, it's always possible for modpack authors to just hide/remove the Mo' Creatures alt saddle if they want.

**Comment by IcarussOne** [comment]
Change of plans due to concerns about compatibility with other mods that utilize saddles. :)

Crafted saddle has been replaced with a configurable saddle recipe (true by default), thankfully the removal shouldn't be too intrusive.
