### ISSUE TITLE
(Aquatic) entities from other mods won't spawn

### ISSUE THREAD

**Issue by NinetyKnight99** [Elite-Modding-Team/MoCreaturesExtended#126]
I was testing the mod and noticed  in the ocean the  problem of incompatibility continues with others mods.

those mods are: zoo and wild, better animal plus and abyssal deeps (other mods that add  sea creatures such as animalium or ice and fire do not have that problem and the mobs do spawn)

the creatures from these mods do not spawn in the ocean, only the creatures from mo creatures .

I already tried the aforementioned mods separately along with the mo creatures mod, modifying the number of creatures that can spawn by lowering the values ​​of mo creatures and increasing the values ​​of the other mods and the problem persisted.

**Comment by ACGaming** [comment]
Please test with this new build: https://github.com/ACGaming/MoCreaturesExtended/actions/runs/7949586490/artifacts/1254598783

Extract the .zip file and use the .jar file without the `-dev` tag.

There are two new config settings for that matter, please set `WorldGenSpawningWaterCreatures` in `MoCSettings.cfg` to `false` and test again.

**Comment by NinetyKnight99** [comment]
I had problems with my equipment and I had to send it to be fixed, I was recently able to check the game again and I discovered that the mod is not the problem, it turns out that when I leave and enter the world the sea mobs from other mods already appear, this is some external error with another mod that causes the same error with other mods causing the creatures to not appear until one exits and re-enters the created world (I suspect the bug is from the zawa mod)

I apologize for the false alarm and the possible loss of time it causes.

**Comment by ACGaming** [comment]
No worries, thanks for the explanation. From my testing, both spawning on land and in water is working fine with popular animal mods in the latest development state. Aquatic spawns are sophisticated, so chance is the developers of other water-related animal mods are doing something tricky to accomplish them.

**Comment by NinetyKnight99** [comment]
I have been doing more tests, I already removed all the mods, I already deleted all the configurations, I did tests without Zawa, using only the abyssaldephts and better animal plus mods and the error persisted.

I don't know what happened that caused animals from other mods and mo creatures to appear at the same time during one of the tests, but again the error returned.

  If I remove the mo creatures mod, the animals from better animal pluss and abyssaldepths spawn again.

**Comment by ACGaming** [comment]
> Please test with this new build: https://github.com/ACGaming/MoCreaturesExtended/actions/runs/7949586490/artifacts/1254598783
> 
> Extract the .zip file and use the .jar file without the `-dev` tag.
> 
> There are two new config settings for that matter, please set `WorldGenSpawningWaterCreatures` in `MoCSettings.cfg` to `false` and test again.

Have you tried this yet?

Additionally, you can increase the limits of water creature spawns with [**Universal Tweaks**](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks) as shown here:
![Spawn Caps](https://i.imgur.com/roFRXXm.png)

**Comment by NinetyKnight99** [comment]
> > Please test with this new build: https://github.com/ACGaming/MoCreaturesExtended/actions/runs/7949586490/artifacts/1254598783
> > Extract the .zip file and use the .jar file without the `-dev` tag.
> > There are two new config settings for that matter, please set `WorldGenSpawningWaterCreatures` in `MoCSettings.cfg` to `false` and test again.
> 
> Have you tried this yet?
> 
> Additionally, you can increase the limits of water creature spawns with [**Universal Tweaks**](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks) as shown here: ![Spawn Caps](https://camo.githubusercontent.com/3bbe4e0b942c5d729becde27c0598e75bbd0543df20331e6762361646681248c/68747470733a2f2f692e696d6775722e636f6d2f726f465258586d2e706e67)

This mod makes my Minecraft always crashes and I can never open the game

**Comment by ACGaming** [comment]
Did you install the necessary dependencies [ConfigAnytime](https://www.curseforge.com/minecraft/mc-mods/configanytime) and [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) as well?

**Comment by NinetyKnight99** [comment]
> Did you install the necessary dependencies [ConfigAnytime](https://www.curseforge.com/minecraft/mc-mods/configanytime) and [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) as well?

I did it and the same thing happened again, it worked for a few moments, animals from mo creatures and the other mods appeared at the same time, but from one moment to the next the glitch occurred again making marine animals from the other mods will stop spawning again.

**Comment by IcarussOne** [comment]
Unfortunately aquatic mobs before 1.13 have different behavior for spawning and despawning even for vanilla. After quite a bit of testing though, there is some strange behaviors going on while `Custom Water Creature Spawning` is enabled so I would keep that disabled in the latest build and use a spawn tweaking mod like BiomeTweaker to amp up all the weights of the desired mobs from those other mods.

**Comment by ACGaming** [comment]
With our new config options `WorldGenSpawningCreatures` for regular creatures and `WorldGenSpawningWaterCreatures` for water creatures, our custom spawning during wold generation is disabled by default to improve compatibility with other mods adding entities. It's possible for the end user to enable these features to achieve a behavior resembling the classic Mo' Creatures feeling with vanilla-friendly means.

Other than that, spawning in our continuation is entirely handled by the vanilla spawning system which is balanced around weights: Entities are set to spawn in specific biomes with specific weights and a global spawn cap. The higher the weight of the respective entity, the more likely it is picked by the spawning system. As Mo' Creatures is adding 80+ creatures, it can effectively 'drown out' other mods' entities. To fine-tune this, we improved the configuration file `MoCreatures.cfg` located under `..\config\MoCreatures`, giving the end user plenty of options to set spawn biomes, weights and the amounts spawned per iteration.

Water creatures are more special than land creatures, since vanilla spawning for water creatures is solely balanced around squids. Because of this, these entity type has a much smaller spawn cap than others. Changing the values for spawn caps requires coremodding which is not an inherent feature of Mo' Creatures itself. The end user can alter these spawn caps with the widely utilized mod [Universal Tweaks](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks) as shown in this configuration example, emulating the spawn caps of the original Mo' Creatures:
![Spawn Caps](https://i.imgur.com/roFRXXm.png)

With these mentioned tools, it's possible to thoroughly configure spawning of Mo' Creatures entities for any modpack use case. If that should still not suffice, there are additional mods such as [In Control!](https://www.curseforge.com/minecraft/mc-mods/in-control) or [BiomeTweaker](https://www.curseforge.com/minecraft/mc-mods/biometweaker) to control spawning of entities altogether.

**Comment by IcarussOne** [comment]
Should be resolved with default configurations.
