### ISSUE TITLE
Tamed Bunny ride cooldown is not clear to the player

### ISSUE THREAD

**Issue by xJon** [Elite-Modding-Team/MoCreaturesExtended#152]
Often requires multiple clicks. Reproduced with only Mo' Creatures Extended installed, both on singleplayer and on a dedicated server.

**Comment by demonlexe** [comment]
This is a feature, not a bug; "Riding" logic has a cooldown for re-mounting something, it's 60 ticks.

I don't think we should override this with Force, either, because that may cause us some problems later

<img width="800" alt="image" src="https://github.com/user-attachments/assets/a91d5f27-3926-46ee-b269-0dcf1ce326dd">

**Comment by xJon** [comment]
@demonlexe Maybe during the cooldown we should add a little status message, so it's clearer?

**Comment by demonlexe** [comment]
What could that look like? I think a chat message would be too spammy, but maybe we can do a small line of text above the XP bar? Do we have an example of that somewhere
@xJon

**Comment by xJon** [comment]
Sent examples in Discord 🙃

**Comment by demonlexe** [comment]
Decided on displaying a message above the XP bar, "Almost there! Your pet needs {time_left} more ticks before it’s ready to join you."
