### ISSUE TITLE
Problems with Kitties/Kitty Bed

### ISSUE THREAD

**Issue by MrBluSpy** [Elite-Modding-Team/MoCreaturesExtended#45]
Recently downloaded the new mod since I heard it was updated and it fixed most of the problems with the original mod but when I was testing it out with the kitties it still had the same problems as the old mod. My kitties were moving really fast in a circle as if they were glitched. Now the problem with the Kitty Bed is that they use the beds to eat but when they're supposed to get off, they don't. They just stay there and I have to either remove them or the Kitty Bed itself which is really annoying. It's also the same if you were to breed them.

**Comment by ACGaming** [comment]
Fixing issues with the mod is a continuous process for the foreseeable future. Kitties and their logic are a good example. They have 20+ different undocumented states which need to be dissected. Because our time is limited and there‘s so much to fix on all ends, we have to prioritize what we can work on.

**Comment by ACGaming** [comment]
Resolved with 96c8d34bdf6a9c3ea3ea8ade183e1ed6285f7a0a for the upcoming update!
