### ISSUE TITLE
Incompatibility with Minor Integrations and Additions (MIA)

### ISSUE THREAD

**Issue by Ldawsonm** [Elite-Modding-Team/MoCreaturesExtended#57]
I don't know if this issue is relevant here, as MIA was responsible for the crash, not this mod. I've gone ahead and made an issue on its issue tracker, but I wanted to make this post here as that mod has not been updated in over a year, so I doubt they'll make the fix.

Anyway, with the latest update, which reorganizes the class file structure, other mods that integrate with Mo' Creatures break since they are trying to reference an entity class file that is not located where it thinks it is. Example:
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minor Integrations and Additions (mia)
Caused by: java.lang.NoClassDefFoundError: drzhark/mocreatures/entity/passive/MoCEntitySnake`

Again, this issue technically is not relevant here since MIA caused the crash, not Mo' Creatures. However, I'm sure there are other mods that integrate with Mo' Creatures that will run into similar problems. I just wanted to make this known because this means that users may have to choose between having Mo' Creatures Extended over regular Mo' Creatures, not have the integrating mod, or not updating Mo' Creatures Extended in order for their modpacks to function.

Edit: To fix this issue for myself, I've just reversed the update

**Comment by ACGaming** [comment]
MIA specifically targets the old Mo‘ Creatures via class structure and thus fails in the process.

Because we know what we‘re doing with reorganizing the internal structure, we have taken care of the majority of integrations for Mo‘ Creatures Extended ourselves. This is the first point of the changelog.

Just disable the various crashing/overlapping integrations in the Mo‘ Creatures config file from MIA and you won‘t have to sacrifice anything.

**Comment by Ldawsonm** [comment]
I did what you said, and it works perfectly. Thank you!

Edit: I also wanna say thank you for continuing to maintain Mo' Creatures! I personally believe it's the best creatures mod and its a shame that it was abandoned for so long, so thank you guys for picking up the torch!
